### ISSUE TITLE
problem plotting distribution object

### ISSUE THREAD

**Issue by LaurentFranckx** [csgillespie/poweRlaw#40]
I don't know whether this is a bug, or whether I did something wrong, but when I try to plot my distribution object, I get the following error message: 

> plot(USBlogFreqPow)
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' and 'y' lengths differ

However, I do not see any problem with the actual object:

> USBlogFreqPow
Reference class object of class "displ"
Field "xmin": 
[1] 2
Field "pars": 
[1] 1.526647
Field "no_pars": 
[1] 1

The vector with the distribution is appr 250000 elements long.

I use a 64 bit Windows 7 machine and R version 3.1.0 (2014-04-10) -- "Spring Dance"

**Comment by csgillespie** [comment]
Can you send me your data set or put it online?

**Comment by LaurentFranckx** [comment]
Here's the link to the file
https://github.com/LaurentFranckx/eindwerk/blob/master/US.blogsunique.txt 


Here's the complete chunk of code I used:

USBlogFreq <- read.table("en_US_blogsunique.txt", stringsAsFactors = FALSE)
TestFreqTable <- USBlogFreq
names(TestFreqTable) <- c("freq", "word")
TestFreqTable <- TestFreqTable[order(TestFreqTable$freq, decreasing =
TRUE), ]
freq_count <- TestFreqTable$freq
FreqPow <- displ$new(freq_count)
FreqPowMin <- estimate_xmin(FreqPow, pars = NULL)
FreqPow$setXmin(FreqPowMin)
plot(FreqPow)

Also note that the following code *did* work:

y <- FreqPow$internal$freq
x <- FreqPow$internal$values
plot(log(x),log(y))

**Comment by LaurentFranckx** [comment]
Now that I have seen the plot, I also have some doubts that a power function is really the most appropriate fit. But running bootstrap_p() takes me hours (which is certainly due to the size of the object)

**Comment by LaurentFranckx** [comment]
What might also be relevant is that I get the following when I run plot() in debug mode:

> debug(plot)
> plot(FreqPow)
debugging in: plot(FreqPow)
debug: standardGeneric("plot")
Browse[2]> summary(x)
Length  Class   Mode 
     1  displ     S4 
Browse[2]> ls()
[1] "x" "y"
Browse[2]> summary(y)
Error in summary(y) : argument "y" is missing, with no default
Browse[2]> str(x$internal)
List of 11
 $ freq    : int [1:3511] 81854 27381 14798 9846 7163 5255 4299 3429 2941 2572 ...
 $ values  : num [1:3511] 1 2 3 4 5 6 7 8 9 10 ...
 $ cum_slx : num [1:3511] 317527 317527 298548 282291 268642 ...
 $ cum_n   : int [1:3511] 212227 130373 102992 88194 78348 71185 65930 61631 58202 55261 ...
 $ dat     : int [1:212227] 1 1 1 1 1 1 1 1 1 1 ...
 $ xmin    : int 1
 $ v       : int [1:2] 1 0
 $ slx     : num 317527
 $ n       : int 212227
 $ pars    : num 1.5
 $ constant: num 2.6

**Comment by csgillespie** [comment]
Thanks for the report. I figured out what the issue was and a fix is now in github. As an aside, you can speed up estimating `xmin` and hence bootstrapping by explicitly stating the xmins to search, i.e.

```r
estimate_xmin(m, xmins = 1:10)
```
Thanks

**Comment by LaurentFranckx** [comment]
You're welcome - I should thank you for the package. Things work fine now.

**Comment by JuanPichardo** [comment]
Hi, i have the same problem. I understand that there is a new package, but i don't understand how do you do to update the package... Do you help me, please?

**Comment by JuanPichardo** [comment]
I understand now, thank you.

**Comment by csgillespie** [comment]
Now on CRAN - version 0.30.2

**Comment by bfbraum** [comment]
I hate to say it, but I'm having the same problem:

>data.series <- c(0.023467568, 1.533181588, 0.667740148, 0.173541143, 0.325009479, 0.031038846, 0.153627984, 1.525853456, 0.057910586, 0.284331442, 0.567665758, 0.036915353, 0.030041758, 0.274574410, 0.077930435, 0.049086982, 0.447652110, 0.423262507, 26.076716016, 2.394246206, 3.521126761, 2.236890644, 0.246581040, 2.074805506, 0.750750751, 0.029104309, 0.032375032, 0.066493783, 0.040100551, 0.007162336, 0.003959062, 0.796929456, 0.408163265, 0.508905852, 0.414628079, 2.598472605, 0.329326527, 1.554071410, 13.586656994, 0.354838710, 0.034693311, 0.049381335, 0.081319381, 0.600885706, 0.770030416, 2.786757329, 0.005066466, 0.106605641, 0.429096853, 26.249575071, 0.353394353, 0.007256003, 0.115493922, 0.767520996, 0.058855677, 1.659844705, 11.524400205, 0.259976602, 0.008198603, 0.888827686, 0.003834436, 0.026707019, 0.011576140, 0.013089280, 0.002784628, 0.001633219, 0.011855451, 0.474289171, 0.319059614, 0.148999362, 0.025577804, 0.018288897, 0.050042559, 0.221937011, 2.618578478, 0.037804325, 0.041322314, 0.198859870, 0.020232598, 0.088655102, 0.135600115, 0.011737254, 0.124230596, 0.003428635, 0.900191291, 18.170981669, 0.070780418, 0.271123299, 1.252572247, 0.042866941, 0.007999527, 0.001018788, 1.806820748, 0.008404155, 0.018102665)

>d_pl <- conpl$new(data.series)
xmin.est <- estimate_xmin(d_pl)
d_pl$setXmin(xmin.est)
plot(d_pl)

produces

>Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' and 'y' lengths differ

Any suggestions? Thanks in advance!

**Comment by csgillespie** [comment]
What version of the package are you using?   Try install.packages ("poweRlaw") to make sure you are up to date

**Comment by bfbraum** [comment]
Sorry. I'm using poweRlaw version 0.30.2, with R version 3.2.0, on platform x86_64-apple-darwin13.4.0 (64-bit). I reinstalled to be sure, and I still get the same error.

**Comment by csgillespie** [comment]
Can I get a copy of the data?

**Comment by bfbraum** [comment]
Hi... I included the data in the example code. Is it not reading in for some reason?

Sent from a mobile device; please pardon brevity and typos.

On May 28, 2015, at 12:25 PM, Colin Gillespie <notifications@github.com<mailto:notifications@github.com>> wrote:


Can I get a copy of the data?

**Comment by csgillespie** [comment]
Sorry - not sure how I missed the data set. I'll look into it

**Comment by csgillespie** [comment]
@bfbraum I think I've found the error. I intend to write a few additional tests for the package to catch this in the future (probably on Friday). Then I'll update CRAN next week. In the meantime,  install the github version a fix.

Thanks
