### ISSUE TITLE
running "plot" in Rmd files with cache =   TRUE

### ISSUE THREAD

**Issue by LaurentFranckx** [csgillespie/poweRlaw#41]
Hi, 
It seems like a have another issue with plot() now. I am running some functions in R chunks in an RMd file, and I get an error:
![ploterrorinrmd](https://cloud.githubusercontent.com/assets/7197752/6747658/bfd2c728-cedc-11e4-9f0f-03b185289232.PNG)
I think this is linked to the fact the the previous chunk was run with cache= TRUE, because I did not have a problem when cache=FALSE. When I comment out the following lines:
```r
plot(FreqPow)
lines(FreqPow)
```
then the other lines in the same chunk work perfectly:
```r
summary(FreqPow$internal)
df <- cbind(FreqPow$internal$freq,FreqPow$internal$values)
head(df)
tail(df)
head(TestFreqTable)
tail(TestFreqTable)
```

**Comment by csgillespie** [comment]
I have the same problem when building vignettes. This is more to do with knitr than this package. Perhaps more granular caches (http://yihui.name/knitr/demo/cache/) would help.
