### ISSUE TITLE
Differences in estimation with a big dataset

### ISSUE THREAD

**Issue by lsaravia** [csgillespie/poweRlaw#45]
I am fitting power laws with a big (10^6) data set, I suspected that there was some problem with alpha, so  I tried the pareto.R functions from Shalizi <http://tuvalu.santafe.edu/~aaronc/powerlaws/>, and it gives me different results 

![plawestimationcomp](https://cloud.githubusercontent.com/assets/1203501/7715061/9ed8ca60-fe5a-11e4-830a-02c7348a8a38.png)

the code I used is here

https://github.com/lsaravia/CriticalGlobalForest/blob/master/R/test_poweRlaw.r

**Comment by csgillespie** [comment]
Thanks for the feedback.

 * Could I get a copy of the date (simulated or otherwise)
 * Your url doesn't work.

Cheers

**Comment by lsaravia** [comment]
My mistake, I have used the function pareto.fit instead of zeta.fit, after correct that the results are identical. Anyway I wonder why if you look at the figure, the continuous power law seems to fit better.

The code is here 

https://www.dropbox.com/sh/91ywo3x510z4ozk/AABafDJY9GQ9BM-sVDsNaXQca?dl=0

and the data

https://www.dropbox.com/s/u6zq51mqhnkqxiy/MOD44B.MRTWEB.A2010065.005.Percent_Tree_Cover.tif.bin?dl=0

Cheers!

**Comment by csgillespie** [comment]
Sorry for the delay. I responded a few days ago, but most have forgotten hit comment.

Anyway, I've noticed in types of data, the Clausett et al method doesn't work that well; it's the downside for having a nice flexible method.

I'm working on other methods, would it be possible to include you dataset in the paper as an example?

Thanks

**Comment by lsaravia** [comment]
Yes you could, but I guess that the problem is that the data is originally continuous (tree patch size), and it is discretized by the remote sensing image, so the continuous function fits better.
Soon I will deposite the data in a public repository, in the meantime you could use it.

**Comment by csgillespie** [comment]
Great. Do you have a paper I could cite?

**Comment by lsaravia** [comment]
Not yet... but I will let you know

**Comment by csgillespie** [comment]
As an aside, there is a bug in http://tuvalu.santafe.edu/~aaronc/powerlaws/plfit.r when the data is discrete and `xmin=1`.
