### ISSUE TITLE
bootstrap_p error on dispois$new() object

### ISSUE THREAD

**Issue by spiros2** [csgillespie/poweRlaw#47]
I can apply bootstrap_p function to any object type displm, dislnorm & disexp but not to dispois. It gives me the following error:

> library(poweRlaw)
> x <- c(1,1,1,2,2,3,11)
> m = dispois$new(x)
> m$setXmin(estimate_xmin(m))
> m$setPars(estimate_pars(m))
> bootstrap_p(m, no_of_sims=1, threads=1)

Error in checkForRemoteErrors(val) : 
  one node produced an error: unable to find an inherited method for function 'dist_rand' for signature '"dispois"'

**Comment by csgillespie** [comment]
There currently isn't a random number generator available for the truncated Poisson (but it just give a nicer error). 

However, I've thought of an efficient way of generating random numbers from this distribution, so it should be implemented soon.

**Comment by linzhp** [comment]
`bootstrap_p` can support Poisson distribution objects too, right? So don't forget to update the documentation of `bootstrap_p`.
