### ISSUE TITLE
Question about plotting with an external cumulative distribution function

### ISSUE THREAD

**Issue by lsaravia** [csgillespie/poweRlaw#48]
I fit power law, and exponential distributions using your package, and I fit power law w/exponential cutoff with the code by Cosma Shalizi, when I try to plot it the Power w/exponential is shifted upwards like this
![image](https://cloud.githubusercontent.com/assets/1203501/8298152/420329b0-193b-11e5-9f12-0eb6d3d21027.png)

the question how I make the lines to start at the same place? 
The code I use is like this

```
m = conpl$new()
m$setXmin(1);m$setPars(2.1)
# 
#Generate random numbers            #
# 
testP <- dist_rand(m, 100)
m$setXmin(30);m$setPars(2.5)
testP <- c(testP,dist_rand(m, 100))

m <- conpl$new(testP)
(est = estimate_xmin(m))


plot(m,xlab="Area",ylab="CCDF")
m$setPars(est$pars)
m$setXmin(est$xmin) 
lines(m,col=2)

(est1 <- powerexp.fit(testP,est$xmin))
x <- sort(unique(testP))
y <- ppowerexp(x,est1$xmin,est1$exponent,est1$rate,lower.tail=F)
lines(x,y,col=3)
```

**Comment by lsaravia** [comment]
I found a solution that seem to works: 

	po<-plot(m,xlab="Area",ylab="CCDF")
	m$setPars(est$pars)
	m$setXmin(est$xmin) 
	lines(m,col=2)
	
	(est1 <- powerexp.fit(testP,est$xmin))
	x <- sort(unique(testP))
	x <- x[x>=est1$xmin]
	shift <- max(po[po$x>=est1$xmin,]$y)
	
	y <- ppowerexp(x,est1$xmin,est1$exponent,est1$rate,lower.tail=F)*shift
	lines(x,y,col=3)

![image](https://cloud.githubusercontent.com/assets/1203501/8316354/bfe14074-19cc-11e5-8e1d-b12ae840f79e.png)

**Comment by csgillespie** [comment]
Excellent and thanks for the code.  I'll include it in a future vignette.

**Comment by lsaravia** [comment]
Thanks!, but I found that the lognormal distribution doesn't plot with the shift:

	m <- conlnorm$new(x)
	m$setXmin(est1$xmin)
	(est2<-estimate_pars(m))
	m$setPars(est2$pars)
	lines(m, col=5)

![image](https://cloud.githubusercontent.com/assets/1203501/8316717/2a81a7be-19cf-11e5-85ca-4a5a7ee598e1.png)

**Comment by csgillespie** [comment]
The lognormal example should work if you use:

```
m <- conlnorm$new(testP)
m$setXmin(est1$xmin)
(est2<-estimate_pars(m))
m$setPars(est2$pars)
lines(m, col=5)
```
