### ISSUE TITLE
powerlaw graph plot issue

### ISSUE THREAD

**Issue by faeza** [csgillespie/poweRlaw#49]
i have a dataset having centralities of a network, i want to fit poweRlaw distributions on data. My dataset (Centralities) have alot of zeroes except "Degree centrality". When i run commands: "conpl" on the centralities one by one, it gives me errors ; Commands i am using are given below:

v=fun.zero.omit(Centrality1InDegree) mpl=conplnew(v) plot(m_pl) Error i get :Error in xy.coords(x, y, xlabel, ylabel, log) : 'x' and 'y' lengths differ Kindly guide me where i am doing wrong...Your help will be appreciated!

**Comment by csgillespie** [comment]
Would you update to the latest github version and try again.

**Comment by faeza** [comment]
Okay... thanks

**Comment by faeza** [comment]
Okay..thanks :)

Best RegardsFaizaStudent MS SE,COSMOSE Research Grouphttp://ww3.comsats.edu.pk/cosmose/Date: Fri, 26 Jun 2015 03:40:26 -0700

**Comment by csgillespie** [comment]
Does the plot now work?

**Comment by faeza** [comment]
yes they worked by changing commands... in the same package! thanksFaizaSent from Samsung mobile Colin Gillespie  wrote:Does the plot now work?

**Comment by faeza** [comment]
Hi I need some help regarding my poweRlaw plots, i am trying since long, As actually i am new in R and have never done programming and stats,so may be i ask bit lame questions.... Sorry for that:When i run commands on discrete data:>newdata<-Data[Data$Eccentricity!=0,]>m_pl=displ$new(newdata$Eccentricity)> plot(m_pl)This works and give me plot.

But when i run same commands on continous data:>newdata<-Data[Data$Eigenvector.Centrality!=0,] >m_pl=conpl$new(newdata$Eigenvector.Centrality) >est=estimate_xmin(m_pl)> m_pl$setXmin(est)> plot(m_pl)It gives me Error:Error in xy.coords(x, y, xlabel, ylabel, log) :   'x' and 'y' lengths differKindly help me doing thiis where i am wrong and what i need to do.Thanks

Best RegardsFaizaStudent MS SE,COSMOSE Research Grouphttp://ww3.comsats.edu.pk/cosmose/Date: Thu, 2 Jul 2015 04:42:47 -0700

**Comment by csgillespie** [comment]
I need access to you data, as I can reproduce this error

**Comment by faeza** [comment]
HiHere is my data...

Best RegardsFaizaStudent MS SE,COSMOSE Research Grouphttp://ww3.comsats.edu.pk/cosmose/Date: Wed, 8 Jul 2015 01:04:14 -0700

**Comment by csgillespie** [comment]
I can't see your data? Did you mean to include a URL?

**Comment by faeza** [comment]
I have attached the file... is there some other way?

Best RegardsFaizaStudent MS SE,COSMOSE Research Grouphttp://ww3.comsats.edu.pk/cosmose/Date: Thu, 9 Jul 2015 12:44:41 -0700

**Comment by csgillespie** [comment]
Try adding it to a https://gist.github.com/

**Comment by faeza** [comment]
https://gist.github.com/faeza/3d39fbc2948deee4b41c/revisions

Best RegardsFaizaStudent MS SE,COSMOSE Research Grouphttp://ww3.comsats.edu.pk/cosmose/Date: Thu, 9 Jul 2015 13:31:55 -0700

**Comment by csgillespie** [comment]
This works for me with the latest version:

```
devtools::install_github("csgillespie/poweRlaw", sub="pkg")
```

**Comment by faeza** [comment]
Thanks you so much.

Best RegardsFaizaStudent MS SE,COSMOSE Research Grouphttp://ww3.comsats.edu.pk/cosmose/Date: Thu, 9 Jul 2015 14:40:59 -0700
