### ISSUE TITLE
bootstrap_p issue, could not find function "get_n"

### ISSUE THREAD

**Issue by AnaCG** [csgillespie/poweRlaw#53]
Greetings. I am working with a very large dataset, in the form of dataframe (4635810 elements). The error is at the end of the message, I hope you have had this issue before and can tell me what I am doing wrong. 
It is really complicated to provide the dataset, never the less these are the commands I am applying:
alldeg<-the 4635810 elements
deg_pl<-displ$new(alldeg)
est<-estimate_xmin(deg_pl)
deg_pl$xmin<-est

print("KS statistic for power law distribution")
print(est$KS)

bs<-bootstrap_p(deg_pl)

At this point, I get the following error:
Error in checkForRemoteErrors(val) :
  one node produced an error: could not find function "get_n"
Calls: bootstrap_p ... clusterApply -> staticClusterApply -> checkForRemoteErrors

**Comment by csgillespie** [comment]
Ok. I think I know what's wrong.  I'll fix on Monday.

**Comment by csgillespie** [comment]
I couldn't reproduce your error, but I think I may still be able to fix it. Would you try out the fix and let me know. Thanks

**Comment by AnaCG** [comment]
Ok thank you, I'll let you know if this helped!

**Comment by AnaCG** [comment]
Hey! sorry but I could not solve the error, I have a smaller 685KB dataset that I can email to you for you to replicate the error.

**Comment by csgillespie** [comment]
To double check I presume you used the github version

**Comment by csgillespie** [comment]
@AnaCG  Did you use the github version?
