### ISSUE TITLE
Enhancement request: Test for change in scaling coefficients

### ISSUE THREAD

**Issue by bfbraum** [csgillespie/poweRlaw#55]
It'd be really nice, if possible, to implement a test of whether the scaling coefficient in one subset of the data differs significantly from the scaling coefficient in another subset. Structural changes can take the form of a change in scaling coefficients over time (see, e.g., Cederman, Lars-Erik, T. Warren, and Didier Sornette. “Testing Clausewitz: Nationalism, Mass Mobilization, and the Severity of War.” International Organization 65, no. 04 (2011): 605–38, at 623), and it'd be very useful to have a formal test, if it's not too much trouble. Thanks!

**Comment by csgillespie** [comment]
Thanks for the suggestion. Does the suggested paper propose a test? 

If possible, could you give a little piece of R code demonstrating the test? You don't have to worry how it would fit in the package, I would sort that out

Thanks

**Comment by bfbraum** [comment]
They seem to use a straightforward F-test:

> In fact, based on a test of the ratio a1/a2, we can reject the null hypothesis of equal distributions with a high degree of statistical confidence (p=0.0045). ... Here we make use of the fact that the ratio a1/a2 of the estimated exponents, corresponding to two independent samples of size n1 and n2 that are generated from the same power law, is distributed according to the F-distribution with (2n2, 2n1) degrees of freedom.

I haven't been able to reproduce that exact result using that method, though, and I haven't seen it used elsewhere. A more promising technique -- at http://stats.stackexchange.com/questions/139612/can-i-use-likelihood-ratio-test-to-compare-two-samples-drawn-from-power-law-dist -- is a likelihood ratio test, which would require only the log-likelihoods of the pooled vs. separate samples. I assume that the samples in question are *only* the samples at the tails of the distribution, i.e., x>x_min.

The simplest and most intuitive approach, to me anyway, would be to restrict the sample to the tail of the distribution, divide it into two groups, create a binary variable indicating which group the sample is in, and then, instead of estimating

```y = b0 + b1(x)```

via MLE to get the slope coefficient b1, estimate

```y = b0 + b1(x) + b2(group) + b3(x * group)```

and use the significance of b3 as the test of different slopes/scaling coefficients.

Sorry for the long-winded answer, but I wanted to cover all bases :-)

**Comment by bfbraum** [comment]
Actually, it just hit me that I might be overthinking this. You already use the bootstrap to estimate the parameter uncertainty, right? Why not do that twice, once for each subset of the data, and then simply subtract one set of bootstrap estimates from the other? If the difference between the two scaling coefficients is greater than what you'd expect to see by chance, then 0 should lie outside of the 95% confidence intervals of the resulting distribution (which should be Normal, since the two original distributions are Normal).

Best of all, since you left the bootstrap estimates where I can easily grab them, I can do this myself and there's no need to tweak the package. :-)

**Comment by csgillespie** [comment]
Good idea, that makes life much simpler for everyone. 

If you can be bothered, feel free to write a little markdown document and I'll include it in the package as a vignette.
