### ISSUE TITLE
p-value for log-norm

### ISSUE THREAD

**Issue by JuanPichardo** [csgillespie/poweRlaw#58]
Hi

I have used the function "bootstrap_p" for log-norm distribution objects and I have obtained a result for p-value, but in the function's documentation says that "function only available for power law distribution objects". My question is: Do it have sense p-value for log-norm?

Thank you.

**Comment by csgillespie** [comment]
The docs are out of date. In the early package releases, the only RNG I had was the powerlaw. I've now added others.
