### ISSUE TITLE
Test-statistic for the discrete exponential distribution

### ISSUE THREAD

**Issue by dbmehta** [csgillespie/poweRlaw#62]
Hi,
I am trying to reproduce results for the Moby Dick words data as given in Table 6.3 in http://arxiv.org/pdf/0706.1062v2.pdf. For some reason, while comparing the discrete power law distribution with discrete exponential distribution I am getting test-statistic ~ 5.459498 whereas in the Clauset et al paper it is 9.09. But since the other numbers nicely compare with those in the paper, I just wanted to make sure if that the exponential dist numbers are fine. I am using the following code:
----
data("moby")
data = moby

m1 = displ$new(data)
m1$setXmin(estimate_xmin(m1))
m2 = dislnorm$new(data)
m2$setXmin(m1$getXmin())
m2$setPars(estimate_pars(m2))
comppowerlnorm = compare_distributions(m1, m2)
comppowerlnorm$p_two_sided
comppowerlnorm$test_statistic

m3 = disexp$new(data)
m3$setXmin(m1$getXmin())
m3$setPars(estimate_pars(m3))
comppowerexp = compare_distributions(m1, m3)
comppowerexp$p_two_sided
comppowerexp$test_statistic

----

Thanks.

**Comment by csgillespie** [comment]
Sorry, this somehow slipped through my net.

In the original paper, when estimating parameters, the authors used a discrete grid parameter search, something like

```
m3$setPars(estimate_pars(m3, pars=seq(0.01, 1, 0.01)))
comppowerexp = compare_distributions(m1, m3)
comppowerexp$p_two_sided
comppowerexp$test_statistic
```
which results in a test statistic of 8.383. In the poweRlaw package, the default is something a bit more sophisticated.

**Comment by dbmehta** [comment]
Thanks a lot!
