### ISSUE TITLE
ntail

### ISSUE THREAD

**Issue by 115zed81** [csgillespie/poweRlaw#71]
Dear Dr. Gilliespie,
I am a senior researcher in the field of epilepsy and I am interested in investigating nonlinear dynamics in the epileptic EEG (electroencephalogram). I do appreciate your R package 'poweRlaw', indeed I have been using this software to identify possible power-law relationships in my datasets. Nevertheless, I have a question about the computed value on the parameter 'ntail'. I noticed that 'ntail' is always equal to the number of the datapoints of the CDF from the xmin to the end of the dataset (after ascendent ordering). This appears discrepant to what shown on the plot, since many points encompassed in the ntail parameter cannot be reasonably considered as belonging to the apparently straight line of the log-log plot of the CDF. However, the distribution functions power-law, log-normal, exponential and poisson seem not fitted over the entire interval of ntail (starting from the xmin)  and they appear correctly fitted solely over the apparent straight line of the log-log plot of the CDF. I wonder whether the ntail parameter is correctly calculated, since I would appreciate to consider also the ntail parameter in order to highlight an interval of frequency bands (i.e. from xmin to xmin+ntail) of the EEG which could be of interest in the epilepsy research.

Thank you for you attention.

**Comment by csgillespie** [comment]
I can't reproduce. Sorry
