### ISSUE TITLE
Use of `<<-`

### ISSUE THREAD

**Issue by LiNk-NY** [csgillespie/poweRlaw#72]
The use of `<<-` is generally not good practice and should be superseded by using a local package environment and setter and getter functions. These should be set on package load and can be changed within your functions by calling the "setter" function. 
See https://github.com/Bioconductor/SOUNDBoard/blob/master/R/zzz.R
for an example. 

```
.onLoad <- function(...) {
.options$set("var", "value")
}

.options <- local({
env <- new.env(parent=emptyenv())
list(
    set = function(var, value) { "set env var here"},
    get = function(var) { "get env var" }
    )
})
```
    
Regards,
Marcel

**Comment by csgillespie** [comment]
I only use <<- inside a _reference class_. This is part of base R and is (sort of like) a function closure.

See https://stat.ethz.ch/R-manual/R-devel/library/methods/html/refClass.html
