### ISSUE TITLE
ERROR: dependency ‘VGAM’ is not available for package ‘poweRlaw’

### ISSUE THREAD

**Issue by BrunoCortez420** [csgillespie/poweRlaw#75]
Hi,
I recently installed RStudio and tried to install the poweRlaw package. It fails with the following error:
`ERROR: dependency ‘VGAM’ is not available for package ‘poweRlaw’`

I then installed `VGAM-data` package and re-run `install.packages("poweRlaw")`, but the same error occurred.

I'm running RStudio on a Ubuntu 16.04 box.

How can I solve this issue?
Thanks

**Comment by csgillespie** [comment]
What version of R are you using, i.e. sessionInfo()

**Comment by BrunoCortez420** [comment]
```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

```

**Comment by csgillespie** [comment]
I think it's a problem with your version of R. I don't have R 3.2 so can't check. Can you update?
