### ISSUE TITLE
How to load words.txt from text file

### ISSUE THREAD

**Issue by datahaus** [csgillespie/poweRlaw#83]
As a test, I'm attempting to load half the moby words from a text file.
I'm still seeing the same chart.  What am I missing?

data("moby", package="poweRlaw")
##moby.data <- read.csv(file="words.txt")
moby.data <- read.csv(file="wordshalf.txt") ## Seems to still show same chart
m_m = displ$new(moby)
m_m$setXmin(5)
m_m$setPars(2)
(est = estimate_pars(m_m))

https://github.gatech.edu/pages/lheyns3/TW-Charts/R-powerlaw/powerlaw.html

**Comment by csgillespie** [comment]
The object moby is from the data `moby` dataset, i.e. 
```
data("moby", package="poweRlaw")
```
Your dataset is called `moby.data`
