### ISSUE TITLE
Issues fitting power law for income distributions 

### ISSUE THREAD

**Issue by LucaGiangregorio** [csgillespie/poweRlaw#86]
Dear Prof. Gillespie, 
as anticipated on [Stackoverflow ](https://stackoverflow.com/questions/58006688/fitting-power-law-for-income-distribution?noredirect=1#comment102427290_58006688) I am having some weird results when fitting a Power Law. 
Specifically, I would like to fit a power law for the right tail of income distribution to adjust the distribution before computing inequality measures. However, using the package poweRlaw with this first country (Denmark), I have some weird results for the estimates of the Xmin. As reported in the link, it is around the 25th percentile, whereas the graphical inspection suggests that the Xmin should be around the 95th percentile. The code I used for the estimation of the Xmin is the following: 
`m_c1<-conpl$new(country2_1$hi100_eur)`
`est=estimate_xmin(m_c1)`
`m_c1$setXmin(est)`

I attach the xlsx file which is the data frame I am using in R for the computations, where the hi100_eur is the total net household income (in Danish coronas). Do you have any idea of what I am doing wrong? 
Thank you for your precious support

[country2_1.xlsx](https://github.com/csgillespie/poweRlaw/files/3632175/country2_1.xlsx)

**Comment by csgillespie** [comment]
When estimate `xmin`, the upper limit is set at `xmax = 1e5` by default (efficiency reasons). Increase `xmax`. I've now added a message to future users to make this clearer.

**Comment by LucaGiangregorio** [comment]
Dear Prof. Gillespie, 
thank you for your clear reply and support. Now I have reasonable results. 
Best,
