### ISSUE TITLE
bootstrap_p for log-normal: Error in checkForRemoteErrors(val): one node produced an error: invalid arguments

### ISSUE THREAD

**Issue by LN381** [csgillespie/poweRlaw#88]
Hi,

first of all thanks for the amazing package!

Sadly, I'm running into some issues when estimating the gof for a discrete log-normal distribution with a high share of ones:

```
data <- c(
  rep(1, 1273),
  rep(2, 76),
  rep(3,22),
  rep(4, 30),
  rep(5,14),
  rep(6,6),
  rep(7,9),
  rep(8,13),
  rep(9,9),
  rep(11,2),
  rep(12,3),
  rep(13,3),
  rep(14,3),
  rep(16,1),
  rep(17,2),
  20,22,23,23,24,24,25,27,28,29,30,35,37,40,42,52,65
)

ln <- dislnorm$new(data)
ln$setXmin(estimate_xmin(ln))

p <- bootstrap_p(ln, no_of_sims = 10)
```
```
Expected total run time for 10 sims, using 1 threads is 18.9 seconds.
Error in checkForRemoteErrors(val) : 
  one node produced an error: invalid arguments
```

The gof estimation for power-law and stretched-exponential distributions on the same data works fine, probably because they have an estimated xmin above 1. The plotted ln object also seems odd to me, as an xmin=2 would probably yield a much better fit. Due to my limited coding capabilities, I have not been able to trace the error down further.

I'm thankful for any help!

**Comment by LN381** [comment]
Here the session.info:
```

R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

[...]

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] poweRlaw_0.70.2

loaded via a namespace (and not attached):
[1] VGAM_1.1-2     compiler_3.6.0 parallel_3.6.0 tools_3.6.0    splines_3.6.0  stats4_3.6.0  
```

**Comment by csgillespie** [comment]
I think this is caused by the bootstrap algorithm picking odd samples, e.g. all unique values. In the latest version, you should get a more informative message. Just pushed to CRAN.

Thanks

**Comment by LN381** [comment]
Hi,

thanks for the fix, but sadly I'm still receiving the same error.

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

[...]

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] poweRlaw_0.70.6

loaded via a namespace (and not attached):
[1] compiler_4.0.0 parallel_4.0.0 tools_4.0.0    pracma_2.2.9  
```

**Comment by csgillespie** [comment]
Ahhh! Can you simplify your data a little to

**Comment by csgillespie** [comment]
The reason for the error is that the estimated parameter values are -899.70 and 24.14. If you generate random numbers with these parameters:
```
rlnorm(10, -900, 24)
```
You get pretty much zero. 

So to generate RNs above your `xmin` value, you need to generate a **lot** of numbers. I use a simple rejection sampler, to generate a few numbers above xmin, I need to generate 10^300 numbers from the log normal distribution - a few too many :(

I've added a (hopefully) helpful error message.

**Comment by LN381** [comment]
Perfect, thanks a lot!
