### ISSUE TITLE
  bootstrap_p and lnorm_test get totally opposite results

### ISSUE THREAD

**Issue by changshuaili** [csgillespie/poweRlaw#96]
it is weird that the p value from "bs_p2 = bootstrap_p(m_ln)" cannot reject the hypothesis that my data follow log-normal distribution. I got a very big p-value, close to 1. It means the data follow lognormal distribution.
But I use "lnorm_test" from package "gfot" to test my data above the lower bound estimated by bootstrap_p, I got a very small p-value, less than 0.001. It means the data do not follow lognormal distribution.
Why are two results almost opposite?

**Comment by changshuaili** [comment]
I tried different datasets, they often get quite differrent results

**Comment by kikko1978** [comment]
Unsubscribe

Il sab 24 apr 2021, 15:07 changshuaili ***@***.***> ha
scritto:

**Comment by csgillespie** [comment]
I need a reproducible example to comment

**Comment by changshuaili** [comment]
pls analyze this dataset of forbes rich list for canada
[Canada-30-2020.xlsx](https://github.com/csgillespie/poweRlaw/files/6371238/Canada-30-2020.xlsx)
@csgillespie
